### ISSUE TITLE
No sound in pspemu when music playback is active

### ISSUE THREAD

**Issue by GrapheneCt** [cuevavirus/MusicPremium#2]
Pspemu sound disappears when music playback is active. When music is paused, sound appears after few seconds.

**Comment by cuevavirus** [comment]
Pspemu also outputs sound through the BGM port so it is exclusive with music playback. Because pspemu outputs at 44.1kHz, it cannot be upsampled to 48kHz and redirected to a main port. It may be possible to redirect to the voice port. For adrenaline however, it opens the voice port for POPS so nothing can be done there.

**Comment by cuevavirus** [comment]
Fixed in v1.0.2.

For users of Adrenaline, I recommend [chovy-sign](https://github.com/KuromeSan/chovy-sign/releases) and [chovy-trans](https://github.com/KuromeSan/chovy-trans/releases).

**Comment by decadent** [comment]
Alas, background music seems to again be broken with Adrenaline v7 =(
